google.maps.__gjsload__('stats', function(_){'use strict';var $2=function(a,b,c){var d=[];_.Nc(a,function(a,c){d.push(c+b+a)});return d.join(c)};var a3=function(a,b,c,d){var e={};e.host=window.document.location&&window.document.location.host||window.location.host;e.v=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e};var xca=function(a){var b={};_.Nc(a,function(a,d){b[(0,window.encodeURIComponent)(d)]=(0,window.encodeURIComponent)(a).replace(/%7C/g,"|")});return $2(b,":",",")};var yca=function(){this.j=new _.wB;this.O=0};
var b3=function(a,b){var c=new window.Image,d=a.O++;a.j.set(d,c);c.onload=c.onerror=function(){c.onload=c.onerror=_.sa;a.j.remove(d)};c.src=b};var zca=function(a,b,c,d){var e=_.R.N[23],f=_.R.N[22];this.$=a;this.na=b;this.oa=null!=e?e:500;this.S=null!=f?f:2;this.U=c;this.T=d;this.O=new _.wB;this.j=0;this.P=_.Ba();c3(this)};var c3=function(a){window.setTimeout(function(){Aca(a);c3(a)},Math.min(a.oa*Math.pow(a.S,a.j),2147483647))};var d3=function(a,b,c){a.O.set(b,c)};
var Aca=function(a){var b=a3(a.na,a.U,a.T,void 0);b.t=a.j+"-"+(_.Ba()-a.P);a.O.forEach(function(a,d){var e=a();0<e&&(b[d]=Number(e.toFixed(2))+(_.Ck()?"":"-if"))});a.$.j({ev:"api_snap"},b);++a.j};var e3=function(a,b,c,d,e){this.T=a;this.$=b;this.S=c;this.O=d;this.P=e;this.j=new _.wB;this.U=_.Ba()};var f3=function(a,b){this.S=b;this.P=a+"/maps/gen_204";this.O=new yca};var g3=function(){this.N=new _.wB};var Bca=function(a){var b=0,c=0;a.N.forEach(function(a){b+=a.dr;c+=a.Eq});return c?b/c:0};
var h3=function(a,b,c,d,e){this.U=a;this.$=b;this.T=c;this.P=d;this.S=e;this.O={};this.j=[]};var i3=function(a,b,c,d){this.P=a;_.I.bind(this.P,"set_at",this,this.S);_.I.bind(this.P,"insert_at",this,this.S);this.U=b;this.$=c;this.T=d;this.O=0;this.j={};this.S()};var j3=function(){this.j={}};var Cca=function(){this.j=[];this.O=[]};var k3=function(a,b,c){this.j=a;this.O=b;this.P=c};
var Dca=function(a,b){a.j.j.push(b);var c=a.O,d=_.nb(b),c=c.j;d in c||(c[d]=0);++c[d];d=a.j;if(d.j.length+d.O.length>a.P){c=a.j;d=c.O;c=c.j;if(!d.length)for(;c.length;)d.push(c.pop());(d=d.pop())&&a.O.remove(d)}};var l3=function(a,b){this.T=new k3(new Cca,new j3,100);this.O=null;this.Aa=[];this.S=a;_.I.bind(a,"insert_at",this,this.Pe);_.I.bind(a,"set_at",this,this.Pe);_.I.bind(a,"remove_at",this,this.Pe);this.Pe();this.j=0;this.pa=b;this.P=0};
var m3=function(){this.O=_.Ue(_.R);var a;_.vj()?(a=_.Me(_.R).N[11],a=null!=a?a:""):a=_.xx;this.j=new f3(a,_.ci);new i3(_.Zh,(0,_.t)(this.j.j,this.j),_.Jf,!!this.O);a=_.Qe(_.Ye());this.U=a.split(".")[1]||a;_.bi&&(this.P=new zca(this.j,this.U,this.oa,this.O));this.$={};this.T={};this.S={};this.na={};this.oa=_.Te()};
e3.prototype.na=function(a,b){var c=_.ra(b)?b:1;this.j.isEmpty()&&window.setTimeout((0,_.t)(function(){var a=a3(this.$,this.S,this.O,this.P);a.t=_.Ba()-this.U;var b=this.j;_.xB(b);for(var c={},g=0;g<b.j.length;g++){var h=b.j[g];c[h]=b.pa[h]}_.uA(a,c);this.j.clear();this.T.j({ev:"api_maprft"},a)},this),500);c=this.j.get(a,0)+c;this.j.set(a,c)};
f3.prototype.j=function(a,b){var c=b||{},d=_.gj().toString(36);c.src="apiv3";c.token=this.S;c.ts=d.substr(d.length-6);a.cad=xca(c);c=$2(a,"=","&");b3(this.O,this.P+"?target=api&"+c)};f3.prototype.T=function(a){b3(this.O,a)};g3.prototype.j=function(a,b,c){this.N.set(_.nb(a),{dr:b,Eq:c})};h3.prototype.na=function(a){this.O[a]||(this.O[a]=!0,this.j.push(a),2>this.j.length&&_.QA(this,this.oa,500))};
h3.prototype.oa=function(){for(var a=a3(this.$,this.T,this.P,this.S),b=0,c;c=this.j[b];++b)a[c]="1";a.hybrid=+(_.Xj()&&_.Yj());this.j.length=0;this.U.j({ev:"api_mapft"},a)};i3.prototype.S=function(){for(var a;a=this.P.removeAt(0);){var b=a.eq;a=a.timestamp-this.$;++this.O;this.j[b]||(this.j[b]=0);++this.j[b];if(20<=this.O&&!(this.O%5)){var c={};c.s=b;c.sr=this.j[b];c.tr=this.O;c.te=a;c.hc=this.T?"1":"0";this.U({ev:"api_services"},c)}}};j3.prototype.remove=function(a){a=_.nb(a);var b=this.j;a in b&&(--b[a],b[a]||delete b[a])};k3.prototype.contains=function(a){return!!this.O.j[_.nb(a)]};_.x(l3,_.J);_.m=l3.prototype;_.m.Pe=function(){_.G(this.Aa,_.I.removeListener);this.Aa.length=0;var a=this.Aa,b=(0,_.t)(this.Bg,this);this.S.forEach(function(c){a.push(_.I.addListener(c.data,"insert",b))});b()};
_.m.Bg=function(){var a=this.get("bounds");if(this.get("projection")&&a&&this.O){var b={};this.S.forEach((0,_.t)(function(c){c.data.forEach((0,_.t)(function(c){var d=c.rawData;if(0==(""+d.layer).indexOf(this.O.substr(0,5))&&d.features){c=d.id.length;for(var e=_.uJ(d.id),d=d.features,k=0,n;n=d[k];k++){var p=n.id,q;a:{q=n;if(!q.latLngCached){var r=q.a;if(!r){q=null;break a}var v=new _.M(r[0],r[1]),r=e,v=[v.x,v.y],w=(1<<c)/8388608;v[0]/=w;v[1]/=w;v[0]+=r.ra;v[1]+=r.qa;v[0]/=8388608;v[1]/=8388608;r=new _.M(v[0],
v[1]);v=this.get("projection");q.latLngCached=v&&v.fromPointToLatLng(r)}q=q.latLngCached}q&&a.contains(q)&&(b[p]=n)}}},this))},this));var c=this.T,d;for(d in b)c.contains(d)||(++this.j,Dca(c,d));!this.P&&this.j&&(this.P=_.QA(this,this.lo,0))}else _.QA(this,this.Bg,1E3)};_.m.lo=function(){this.P=0;this.j&&(_.kl(this.pa,"smni",this.j),this.j=0)};_.m.mapType_changed=function(){var a=this.get("mapType");this.O=a&&a.Qf};_.m.bounds_changed=function(){this.Bg()};_.m=m3.prototype;_.m.gn=function(a,b){var c=new l3(b,a);c.bindTo("mapType",a.__gm);c.bindTo("zoom",a);c.bindTo("bounds",a);c.bindTo("projection",a)};_.m.Fn=function(a){a=_.nb(a);this.$[a]||(this.$[a]=new h3(this.j,this.U,this.oa,this.O));return this.$[a]};_.m.Dn=function(a){a=_.nb(a);this.T[a]||(this.T[a]=new e3(this.j,this.U,1,this.O));return this.T[a]};_.m.cf=function(a){if(this.P){this.S[a]||(this.S[a]=new _.BC,d3(this.P,a,function(){return b.Zc()}));var b=this.S[a];return b}};
_.m.Cn=function(a){if(this.P){this.na[a]||(this.na[a]=new g3,d3(this.P,a,function(){return Bca(b)}));var b=this.na[a];return b}};var Eca=new m3;_.lc("stats",Eca);});
