google.maps.__gjsload__('stats', function(_){'use strict';var d3=function(a,b,c){var d=[];_.Oc(a,function(a,c){d.push(c+b+a)});return d.join(c)};var e3=function(a,b,c,d){var e={};e.host=window.document.location&&window.document.location.host||window.location.host;e.v=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e};var vca=function(a){var b={};_.Oc(a,function(a,d){b[(0,window.encodeURIComponent)(d)]=(0,window.encodeURIComponent)(a).replace(/%7C/g,"|")});return d3(b,":",",")};var wca=function(){this.j=new _.CB;this.O=0};
var f3=function(a,b){var c=new window.Image,d=a.O++;a.j.set(d,c);c.onload=c.onerror=function(){c.onload=c.onerror=_.sa;a.j.remove(d)};c.src=b};var xca=function(a,b,c,d){var e=_.R.N[23],f=_.R.N[22];this.$=a;this.na=b;this.oa=null!=e?e:500;this.S=null!=f?f:2;this.U=c;this.T=d;this.O=new _.CB;this.j=0;this.P=_.Ba();g3(this)};var g3=function(a){window.setTimeout(function(){yca(a);g3(a)},Math.min(a.oa*Math.pow(a.S,a.j),2147483647))};var h3=function(a,b,c){a.O.set(b,c)};
var yca=function(a){var b=e3(a.na,a.U,a.T,void 0);b.t=a.j+"-"+(_.Ba()-a.P);a.O.forEach(function(a,d){var e=a();0<e&&(b[d]=Number(e.toFixed(2))+(_.Ek()?"":"-if"))});a.$.j({ev:"api_snap"},b);++a.j};var i3=function(a,b,c,d,e){this.T=a;this.$=b;this.S=c;this.O=d;this.P=e;this.j=new _.CB;this.U=_.Ba()};var j3=function(a,b){this.S=b;this.P=a+"/maps/gen_204";this.O=new wca};var k3=function(){this.N=new _.CB};var zca=function(a){var b=0,c=0;a.N.forEach(function(a){b+=a.Yq;c+=a.yq});return c?b/c:0};
var l3=function(a,b,c,d,e){this.U=a;this.$=b;this.T=c;this.P=d;this.S=e;this.O={};this.j=[]};var m3=function(a,b,c,d){this.P=a;_.I.bind(this.P,"set_at",this,this.S);_.I.bind(this.P,"insert_at",this,this.S);this.U=b;this.$=c;this.T=d;this.O=0;this.j={};this.S()};var n3=function(){this.j={}};var Aca=function(){this.j=[];this.O=[]};var o3=function(a,b,c){this.j=a;this.O=b;this.P=c};
var Bca=function(a,b){a.j.j.push(b);var c=a.O,d=_.ob(b),c=c.j;d in c||(c[d]=0);++c[d];d=a.j;if(d.j.length+d.O.length>a.P){c=a.j;d=c.O;c=c.j;if(!d.length)for(;c.length;)d.push(c.pop());(d=d.pop())&&a.O.remove(d)}};var p3=function(a,b){this.T=new o3(new Aca,new n3,100);this.O=null;this.Aa=[];this.S=a;_.I.bind(a,"insert_at",this,this.Oe);_.I.bind(a,"set_at",this,this.Oe);_.I.bind(a,"remove_at",this,this.Oe);this.Oe();this.j=0;this.pa=b;this.P=0};
var q3=function(){this.O=_.Ve(_.R);var a;_.yj()?(a=_.Ne(_.R).N[11],a=null!=a?a:""):a=_.Bx;this.j=new j3(a,_.ei);new m3(_.ai,(0,_.t)(this.j.j,this.j),_.Lf,!!this.O);a=_.Re(_.Ze());this.U=a.split(".")[1]||a;_.di&&(this.P=new xca(this.j,this.U,this.oa,this.O));this.$={};this.T={};this.S={};this.na={};this.oa=_.Ue()};
i3.prototype.na=function(a,b){var c=_.ra(b)?b:1;this.j.isEmpty()&&window.setTimeout((0,_.t)(function(){var a=e3(this.$,this.S,this.O,this.P);a.t=_.Ba()-this.U;var b=this.j;_.DB(b);for(var c={},g=0;g<b.j.length;g++){var h=b.j[g];c[h]=b.pa[h]}_.AA(a,c);this.j.clear();this.T.j({ev:"api_maprft"},a)},this),500);c=this.j.get(a,0)+c;this.j.set(a,c)};
j3.prototype.j=function(a,b){var c=b||{},d=_.jj().toString(36);c.src="apiv3";c.token=this.S;c.ts=d.substr(d.length-6);a.cad=vca(c);c=d3(a,"=","&");f3(this.O,this.P+"?target=api&"+c)};j3.prototype.T=function(a){f3(this.O,a)};k3.prototype.j=function(a,b,c){this.N.set(_.ob(a),{Yq:b,yq:c})};l3.prototype.na=function(a){this.O[a]||(this.O[a]=!0,this.j.push(a),2>this.j.length&&_.WA(this,this.oa,500))};
l3.prototype.oa=function(){for(var a=e3(this.$,this.T,this.P,this.S),b=0,c;c=this.j[b];++b)a[c]="1";a.hybrid=+((_.dk()||!_.ak())&&_.ak());this.j.length=0;this.U.j({ev:"api_mapft"},a)};m3.prototype.S=function(){for(var a;a=this.P.removeAt(0);){var b=a.Zp;a=a.timestamp-this.$;++this.O;this.j[b]||(this.j[b]=0);++this.j[b];if(20<=this.O&&!(this.O%5)){var c={};c.s=b;c.sr=this.j[b];c.tr=this.O;c.te=a;c.hc=this.T?"1":"0";this.U({ev:"api_services"},c)}}};n3.prototype.remove=function(a){a=_.ob(a);var b=this.j;a in b&&(--b[a],b[a]||delete b[a])};o3.prototype.contains=function(a){return!!this.O.j[_.ob(a)]};_.w(p3,_.J);_.m=p3.prototype;_.m.Oe=function(){_.G(this.Aa,_.I.removeListener);this.Aa.length=0;var a=this.Aa,b=(0,_.t)(this.zg,this);this.S.forEach(function(c){a.push(_.I.addListener(c.data,"insert",b))});b()};
_.m.zg=function(){var a=this.get("bounds");if(this.get("projection")&&a&&this.O){var b={};this.S.forEach((0,_.t)(function(c){c.data.forEach((0,_.t)(function(c){var d=c.rawData;if(0==(""+d.layer).indexOf(this.O.substr(0,5))&&d.features){c=d.id.length;for(var e=_.AJ(d.id),d=d.features,k=0,n;n=d[k];k++){var p=n.id,q;a:{q=n;if(!q.latLngCached){var r=q.a;if(!r){q=null;break a}var v=new _.M(r[0],r[1]),r=e,v=[v.x,v.y],x=(1<<c)/8388608;v[0]/=x;v[1]/=x;v[0]+=r.ra;v[1]+=r.qa;v[0]/=8388608;v[1]/=8388608;r=new _.M(v[0],
v[1]);v=this.get("projection");q.latLngCached=v&&v.fromPointToLatLng(r)}q=q.latLngCached}q&&a.contains(q)&&(b[p]=n)}}},this))},this));var c=this.T,d;for(d in b)c.contains(d)||(++this.j,Bca(c,d));!this.P&&this.j&&(this.P=_.WA(this,this.eo,0))}else _.WA(this,this.zg,1E3)};_.m.eo=function(){this.P=0;this.j&&(_.ml(this.pa,"smni",this.j),this.j=0)};_.m.mapType_changed=function(){var a=this.get("mapType");this.O=a&&a.Of};_.m.bounds_changed=function(){this.zg()};_.m=q3.prototype;_.m.Ym=function(a,b){var c=new p3(b,a);c.bindTo("mapType",a.__gm);c.bindTo("zoom",a);c.bindTo("bounds",a);c.bindTo("projection",a)};_.m.An=function(a){a=_.ob(a);this.$[a]||(this.$[a]=new l3(this.j,this.U,this.oa,this.O));return this.$[a]};_.m.yn=function(a){a=_.ob(a);this.T[a]||(this.T[a]=new i3(this.j,this.U,1,this.O));return this.T[a]};_.m.bf=function(a){if(this.P){this.S[a]||(this.S[a]=new _.HC,h3(this.P,a,function(){return b.Zc()}));var b=this.S[a];return b}};
_.m.xn=function(a){if(this.P){this.na[a]||(this.na[a]=new k3,h3(this.P,a,function(){return zca(b)}));var b=this.na[a];return b}};var Cca=new q3;_.mc("stats",Cca);});
